version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - d4:f9:83:ad:c7:cf:31:d7:54:0d:13:8b:9d:36:16:cc
      - run:
          name: Setup Virtual Environment
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv helloworld
            . helloworld/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            python test_hello_world.py
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            . helloworld/bin/activate
            pyinstaller -F hello_world.py
           
      - run:
          name: Deploy app to Linode Producrion Server via Docker
          command: |    
             ssh  -o StrictHostKeyChecking=no   UserKnownHostsFile=/dev/null CheckHostIP=no 34.68.161.68
              
           
