version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 38:6b:72:4a:f3:7b:a7:da:1b:a5:a1:19:0e:af:fa:a6
      - run:
          name: Setup Virtual Environment
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv helloworld
            . helloworld/bin/activate
        
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image to docker registry test
          command: |
            . helloworld/bin/activate     
           
      - run:
          name: Deploy app to Linode Producrion Server via Docker
          command: |            
            ssh -v 34.68.161.68
            ssh -o StrictHostKeyChecking=no 34.68.161.68 "/bin/bash ./deploy_app.sh $DOCKER_LOGIN/$IMAGE_NAME:$TAG"      
              
           
